import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  ArrowRight,
  Braces,
  Clipboard,
  Clock,
  Code,
  Copy,
  Database,
  FileText,
  Globe,
  Hash,
  Home,
  KeyRound,
  Layers,
  LayoutDashboard,
  LucideAngularModule,
  Monitor,
  Scissors,
  Search,
  Settings,
  Shield,
  Terminal,
  Upload,
  Wrench,
  X,
} from 'lucide-angular';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        Search,
        Home,
        LayoutDashboard,
        Wrench,
        ArrowRight,
        Braces,
        KeyRound,
        FileText,
        Shield,
        Terminal,
        Hash,
        Clock,
        Globe,
        Scissors,
        Settings,
        Upload,
        Code,
        Clipboard,
        Monitor,
        Database,
        Layers,
        Copy,
        X,
      }),
    ),
  ],
};
